### ISSUE TITLE
Error shard name (odbc) doesn't match dependency name (crystal-odbc)

### ISSUE THREAD

**Issue by mavu** [naqvis/crystal-odbc#1]
Hi

I tried to install as described and get that error.
```

shards install
Resolving dependencies
Fetching https://github.com/naqvis/crystal-odbc.git
Fetching https://github.com/crystal-lang/crystal-db.git
Error shard name (odbc) doesn't match dependency name (crystal-odbc)
```

**Comment by naqvis** [comment]
@mavu Thanks for pointing the problem. I've updated the README and updated the repo.

   ```yaml
   dependencies:
     odbc:
       github: naqvis/crystal-odbc
   ```
